site_name: Paul M. Garrett
docs_dir: docs
repo_url: 'https://github.com/paulgarrettphd/Site.git'
repo_name: 'GitHub'

theme:
  name: material
  #custom_dir: theme
  site_favicon: img/faveicon.ico
  #logo:
  #  icon: face
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true
  #extra_css: stylesheets/extra.css

nav:
  - Home: index.md
  - COVID-Tracking Australian Wave 1 Results : PressReleaseAnalysis.html
  - COVID-Tracking Australian Wave 2 Results : Wave2Final.html
  - COVID-Tracking Australian Wave 3 COVIDSafe Resuts: Wave3PrelimAnalysis.html
  - COVID-Tracking Australian Wave 4 COVIDSafe Resuts: Wave4PrelimAnalysis.html
  - COVID-Tracking Taiwan Prelim: Mkdown_CT.html
  - COVID-Tracking Taiwan Waves 1-4: TaiwanAttitudesAnalysis.html
  - COVID-Tracking Spain Wave 2: SpainResults.html
  - COVID-Tracking Italy: COVID-tracking-attitudes-Italy.html
  - COVID-Tracking Japan: COVID-tracking-attitudes-Japan.html
  - Functions for plotting COVID by Nation w/ Labelled Dates: NationalCOVIDbyDates.html
  - Academic Projects: Projects.md
  - Edu Materials - Writing: EducationalMaterialsWriting.md
  - Edu Materials - Coding:  EducationalMaterialsCode.md
  - Systems Factorial Technology: SFT.md
  - Media: Media.md
  - Publications: Publications.md
  - Contact Me: Contactme.md
