site_name: Paul M. Garrett
docs_dir: docs
repo_url: 'https://github.com/paulgarrettphd/Site.git'
repo_name: 'GitHub'

theme:
  name: material
  #custom_dir: theme
  site_favicon: img/faveicon.ico
  #logo:
  #  icon: face
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true
  #extra_css: stylesheets/extra.css

nav:
  - Home: index.md
  - Gov Tracking Australian Wave 1 Results : PressReleaseAnalysis.html
  - Gov Tracking Australian Wave 2 Results : Wave2Final.html
  - Gov Tracking Australian Wave 3 COVIDSafe Resuts: Wave3PrelimAnalysis.html
  - Gov Tracking Taiwan Results: Mkdown_CT.html
  - MkDocTestPage: Projects.md
  - Academic Projects: Projects.md
  - Edu Materials - Writing: EducationalMaterialsWriting.md
  - Edu Materials - Coding:  EducationalMaterialsCode.md
  - Systems Factorial Technology: SFT.md
  - Media: Media.md
  - Publications: Publications.md
  - Contact Me: Contactme.md
